### ISSUE TITLE
Gradients in ManifoldDiff?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldDiff.jl#13]
When writing the first example in ManoptExamples.jl,
I noticed that `grad_distance` was still defined in `Manopt.jl`.  I want to move those gradients out - for sure.
Sure, gradient conversion (in Manifold.jl) should stay there since those functions are very manifold-specific.

But besides in the examples, they could also be placed here? We could also collect other simple gradients, though I do not have many in mind for now.

**Comment by mateuszbaran** [comment]
I didn't really need `grad_distance` for anything so I didn't move it. It is very simple so I'm not even sure how useful it is but if you want put it in ManifoldDiff then it's also fine :slightly_smiling_face: .

**Comment by kellertuer** [comment]
We could also keep it in the ManopExample package, I am open to both.

**Comment by mateuszbaran** [comment]
Feel free to put it in the package you prefer :slightly_smiling_face:

**Comment by kellertuer** [comment]
I think it would also fit here well, I will move it then the next days.
