### ISSUE TITLE
Derivatives of geodesics

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldDiff.jl#14]
We could easily add derivatives of geodesics, since they are either

* the parallel transported `X` from `geodesic(M, p, X, t)` to the point `t` (if parallel transport is available)
* or the properly rescaled `log(M, geodesic(M,p,X,t), q)` (divide by the distance of the point at t to q, multiply by the distance pq).

What do you think?

**Comment by mateuszbaran** [comment]
Sure, that would be a nice addition.
