### ISSUE TITLE
Does the Manifolds extension maybe not work?

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/ManifoldDiff.jl#20]
Yesterda< I removed the cache from the Quarto tutorials CI over on Manifolds.jl and merged said PR today. Today the rendering (even in the notebook) there an error

https://juliamanifolds.github.io/Manifolds.jl/latest/tutorials/getstarted.html

I am not sure why that is even happening over there since the tutorial environment and the tutorial do not use ManifoldDiff I think, but the error sounds like it is coming from here?

_edit:_ I get the same error, then I start an empty environment and install Manifolds.jl

**Comment by mateuszbaran** [comment]
Hm, we probably should move the manifolds extension to Manifolds.jl.

**Comment by kellertuer** [comment]
I have not yet understood what the actual error here is and why ProductManifold is not found.

I am not sure for this one, where it fits better. Maybe in Manifolds is better if we consider that the central place.

**Comment by mateuszbaran** [comment]
The error makes little sense to me. Manifolds.jl depends on ManifoldDiff.jl though so moving these parts to Manifolds.jl seems reasonable and would solve this issue.

**Comment by kellertuer** [comment]
sounds good, then lets move that ext.

**Comment by mateuszbaran** [comment]
I will do that then.
